services:
  admin-messanger:
    build: .
    image: admin-messanger
    container_name: admin-messanger
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
